
@url = http://localhost:8080/favorite

GET {{url}}

###

GET {{url}}/2

###

POST {{url}}
Content-Type: application/json
# Authorization: Bearer {{token}}

{
    "url": "https://en.wikipedia.org/wiki/Ada_Lovelace",
    "source": "Wikipedia",
    "creator": null,
    "type": "Reading",
    "title": "Ada Lovelace",
    "description": null,
    "gifUrl": null,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Ada_Byron_daguerreotype_by_Antoine_Claudet_1843_or_1850_-_cropped.png",
    "createdOn": "2000-01-01",
    "updatedOn": "2020-12-31",
    "isCustomTitle": true,
    "isCustomDescription": true,
    "isCustomImage": true,
    "isCustomGif": true
}

###

GET {{url}}/3

###

PUT {{url}}/4
Content-Type: application/json

{
    "id": 4,
    "title": "The Game of Life 60th ANNIVERSARY!",
    "description": "A game that mimics all of life's major decisions",
    "categories": "Development, Family, Dice-Oriented",
    "playerMin": 2,
    "playerMax": 8,
    "releaseYear": 1960,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/403120/header.jpg?t=1682353184"
}

###

DELETE {{url}}/4