@url = http://localhost:8080/security

### Bad credentials... returns 401

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "bad-username",
    "password": "bad-password"
}

### Good credentials... returns 200 with a JWT in the response body

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "john@smith.com",
    "password": "P@ssw0rd!"
}

### Good credentials... returns 200 with a JWT in the response body

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "sally@jones.com",
    "password": "P@ssw0rd!"
}

### Good credentials... returns 200 with a JWT in the response body

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "test@yahoo.com",
    "password": "password56$"
}

### Create new account

POST {{url}}/create-account HTTP/1.1
Content-Type: application/json

{
    "firstName": null,
    "middleName": null,
    "lastName": null,
    "email": "test@yahoo.com",
    "password": "password56$",
    "registeredOn": "2023-07-03",
    "lastLogin": "2023-07-03",
    "enabled": true,
    "roles": ["USER"]
}

### Refresh token... be sure to replace the token in the Authorization header with a valid token

POST {{url}}/refresh_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY2MjU4NjAwOX0.z8fTECKi60szcsgNoyYwaHErhXkOAiYdbaY2rYctcnM

### Create an account... returns 201

POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
    "email": "bob@jones.com",
    "password": "P@ssw0rd!"
}